jobs:
  verify:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./action/workflow

name: Ci

on:
  schedule:
    - cron: "50 0/3 * * *"
